"""Добавлен created_at в users

Revision ID: 91ac54007d1c
Revises: 7bdfcc1065cd
Create Date: 2025-07-25 19:10:05.049644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ac54007d1c'
down_revision: Union[str, Sequence[str], None] = '7bdfcc1065cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('last_donation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_donation_time')
    op.drop_column('users', 'amount')
    # ### end Alembic commands ###
